# Generated by Django 5.0.7 on 2024-08-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cybercrimereport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CybercrimeReport',
        ),
    ]
