# Generated by Django 5.0.7 on 2024-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberCrimeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('hacking', 'Hacking'), ('cyberbullying', 'Cyberbullying'), ('online_fraud', 'Online Fraud'), ('identity_theft', 'Identity Theft')], max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
