# Generated by Django 5.0.7 on 2024-08-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_cybercrimereport_delete_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CyberCrimeReport',
        ),
    ]
