# Generated by Django 5.0.7 on 2024-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.FileField(upload_to='documents'),
        ),
    ]
